"""add ingredients_cleaned to recipe

Revision ID: 47ef026aaff0
Revises: dbdfe10273c8
Create Date: 2025-05-26 02:18:41.371452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ef026aaff0'
down_revision: Union[str, None] = 'dbdfe10273c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients_cleaned', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredients_cleaned')
    # ### end Alembic commands ###
