name: Backend CI

on:
  push:
    branches: [ "main", "dev", "feature/backend-dbapi" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: capstone
          POSTGRES_PASSWORD: capstone10
          POSTGRES_DB: capstone_db
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: capstone10
      POSTGRES_DB: capstone_db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      SESSION_SECRET_KEY: super-secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          source venv/bin/activate
          pytest backend/tests
